name: iosApp
options:
  bundleIdPrefix: com.example.ap2sample
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [iosApp]
    info:
      path: iosApp/Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      SDKROOT: iphoneos
      SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
      ARCHS: "$(ARCHS_STANDARD)"
      VALID_ARCHS: "arm64 x86_64"
      ONLY_ACTIVE_ARCH: YES
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: "NO"
      ENABLE_USER_SCRIPT_SANDBOXING: NO
      SWIFT_VERSION: "5.0"
      FRAMEWORK_SEARCH_PATHS:
        - $(inherited)
        - "$SRCROOT/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
      OTHER_LDFLAGS:
        - $(inherited)
        - -framework ComposeApp
    preBuildScripts:
      - name: Build Kotlin Framework
        script: |
          if [ "YES" = "$COCOAPODS" ]; then
            echo "Skipping Gradle build task"
            exit 0;
          fi
          set -ev
          # Export required env vars for Jetbrains Compose Resources configuration
          export BUILT_PRODUCTS_DIR="${BUILT_PRODUCTS_DIR:-$TARGET_BUILD_DIR}"
          export UNLOCALIZED_RESOURCES_FOLDER_PATH="${UNLOCALIZED_RESOURCES_FOLDER_PATH:-iosApp.app}"

          REPO_ROOT="$SRCROOT/.."
          # To bypass Gradle Daemon environment variable caching issues, we pass env variables as project properties
          "$REPO_ROOT/gradlew" -p "$REPO_ROOT" :composeApp:embedAndSignAppleFrameworkForXcode
